name: Build-Test-Analyze

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install

      - name: Lint Check
        run: yarn lint

      - name: Run Tests
        run: yarn test
        env:
          STAGE: test
          NODE_ENV: testing
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}          
          AWS_REGION: ${{secrets.AWS_DEFAULT_REGION}}

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
